# Generated by Django 3.0.2 on 2020-01-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0002_taskmodel_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='image',
            field=models.ImageField(default='Images/None/No0img.jpg', upload_to='Images/'),
        ),
    ]
